### PR TITLE
Login Class Comments

### PR DESCRIPTION
**Pull request by erinwalker**
Hey Dom, I went through the Login classes and commented them the best that I could. Take a look and let me know if this is what you were looking for and if I got anything wrong.

### CODE REVIEW

**Comment by erinwalker** [comment]
So I pushed my changes and I am positive the comments are there but they are not showing up when I view the code from a web browser.

**Comment by erinwalker** [comment]
Never mind when I view our code side by side I see it there but it doesn't show up when you look at the file directly.

**Comment by erinwalker** [comment]
I changed the author. Let me know if you need me to change anything else.

**Comment by DomAmato** [comment]
nope, some of the comments might be formatted wrong but realistically all that matters for java docs and the documentation site is that something exists for function calls and parameters

**Pull request merged**
